-- Sonic Frontiers
-- 2026-06-12 04:42:50 UTC
-- This Lua was generated by LuaTools to support cerrtain shit

-- First let's add all the appids!
addappid(1237320)
addappid(2079300)
addappid(2079301)
addappid(2089730)
addappid(2089733)
addappid(2089840)
addappid(2093240)

-- Coolio now let's add the decryption keys we need!
addappid(1237321, 1, "9c57e01f36d7bf7a77b07678b08a0e690d785dfbcd9a421ae1fc2157741b5ccd") -- Sonic Frontiers (base)

-- And last but not least, lock the depots to make shit work :3
setManifestid(1237321, "2773324310090316887")
