-- Dead Space
-- 2026-06-12 04:43:30 UTC
-- This Lua was generated by LuaTools to support cerrtain shit

-- First let's add all the appids!
addappid(1693980)
addappid(2164210)

-- Coolio now let's add the decryption keys we need!
addappid(1693981, 1, "9738ac7c4b941978165b403d5785d6c8c331366f7feb30c0b276401fd71f4ccb") -- Dead Space (base)

-- And last but not least, lock the depots to make shit work :3
setManifestid(1693981, "1038276949129655019")
