-- Mafia: The Old Country
-- 2026-06-12 04:39:35 UTC
-- This Lua was generated by LuaTools to support cerrtain shit

-- First let's add all the appids!
addappid(1941540)
addappid(3262000)
addappid(3269260)
addappid(3269270)
addappid(3269280)
addappid(4492700)

-- Coolio now let's add the decryption keys we need!
addappid(1941541, 1, "47c1ea957b9ecc8662a117fa6b19eea01ed30ef06478a364110fe40afa4e9f0e") -- Mafia: The Old Country (base)

-- And last but not least, lock the depots to make shit work :3
setManifestid(1941541, "3121778726057603637")
