-- Sonic Colors: Ultimate
-- 2026-06-12 04:43:44 UTC
-- This Lua was generated by LuaTools to support cerrtain shit

-- First let's add all the appids!
addappid(2055290)
addappid(2129040)
addappid(2154410)
addappid(2189460)
addappid(2189461)
addappid(2189462)
addappid(2189463)

-- Coolio now let's add the decryption keys we need!
addappid(2055291, 1, "35b064414a398875b2ba3c0482f2a5916ea85dd34c317a67157a42a8a6090b51") -- Sonic Colors: Ultimate (base)

-- And last but not least, lock the depots to make shit work :3
setManifestid(2055291, "7074340774677646098")
