-- LEGO® Batman™: Legacy of the Dark Knight
-- 2026-06-12 04:39:06 UTC
-- This Lua was generated by LuaTools to support cerrtain shit

-- First let's add all the appids!
addappid(2215200)
addappid(4168610)
addappid(4168620)
addappid(4168630)
addappid(4168640)
addappid(4468750)

-- Coolio now let's add the decryption keys we need!
addappid(2215201, 1, "5d2bafc1381c29ebabb37bbab50e496548be24f6bf5d511e8d471b99d60cfbf3") -- LEGO® Batman™: Legacy of the Dark Knight (base)

-- And last but not least, lock the depots to make shit work :3
setManifestid(2215201, "8744395932724193069")
