-- Black Myth: Wukong
-- 2026-06-12 04:40:56 UTC
-- This Lua was generated by LuaTools to support cerrtain shit

-- First let's add all the appids!
addappid(2358720)
addappid(2672610)

-- Coolio now let's add the decryption keys we need!
addappid(2358721, 1, "78d5a284965b2206de191dc4ca99d43c9caf5b5e78b47cf0c366fbbb884190d8") -- Black Myth: Wukong (base)

-- And last but not least, lock the depots to make shit work :3
setManifestid(2358721, "8329114521995004621")
