-- DOOM: The Dark Ages
-- 2026-06-12 04:41:55 UTC
-- This Lua was generated by LuaTools to support cerrtain shit

-- First let's add all the appids!
addappid(3017860)
addappid(3363930)
addappid(3363940)
addappid(3469450)
addappid(3698350)

-- Coolio now let's add the decryption keys we need!
addappid(3017862, 1, "b537907a613fd29911d2e311eb41fd2f0b309324601b0ef164c8520562eac290") -- DOOM: The Dark Ages (base)
addappid(3017863, 1, "0c010bdf1623542793fb5765875c715494c4a6c78856f75c124aa7d31f3021cd") -- DOOM: The Dark Ages (base)
addappid(3017864, 1, "35f0d11b6d2b729dd8e5f50a21e7b0300e8d6b79fc6ba487f4198ca6d3402c0d") -- DOOM: The Dark Ages (base)
addappid(3017865, 1, "558521d6ef4cac7a1318bb55268dc878b72482482691e7791ea81bff06c73694") -- DOOM: The Dark Ages (base)
addappid(3017866, 1, "cc9112a06785fd0d7f6e24a50702f1f71e655e35caf8fb3ea09f6036680c0fe4") -- DOOM: The Dark Ages (base)
addappid(3017867, 1, "8ffa78f10846725bed8d48d1a182cf4088f770691c44561b2d167f84fdc60789") -- DOOM: The Dark Ages (base)
addappid(3017868, 1, "fb3bda82e733857d05419dce15179a1aa642b840af21ef69520346fe8a00e20e") -- DOOM: The Dark Ages (base)

-- And last but not least, lock the depots to make shit work :3
setManifestid(3017862, "2294956030765668938")
setManifestid(3017863, "399781073792192298")
setManifestid(3017864, "5126423772771951062")
setManifestid(3017865, "9108580810918908470")
setManifestid(3017866, "9217731964535062300")
setManifestid(3017867, "873442200902637512")
setManifestid(3017868, "1775352278196208271")
