-- Assassin's Creed Shadows
-- Build ID: 23475575
-- This Lua was generated by LuaTools to support cerrtain shit

-- Main AppID
addappid(3159330, 1, "87c39548810f05cc0cf12c9a6a9ff7ae58bbba17ba6fc67d463491b8381b3772")

-- Main Depots
addappid(3159331, 1, "a1a2865a35a1aa7255e0d1a8d6cedab23f2b34346e4a359a283f1a5ceb826ddf") -- (windows, 64-bit)
setManifestid(3159331, "4595780502794590393", 158221014025)
addappid(3159333, 1, "24bbf4e14d616c7df7c56696e444569bcf5689554a6a79f731426e4fac7d66ea") -- French
setManifestid(3159333, "8283686636322166472", 1585414144)
addappid(3159334, 1, "919bdf5d6752a3dfc2cf5f76c6800e25059aeab0489c2ec656e1bb938fef0f13") -- Italian
setManifestid(3159334, "7350092371372350439", 1833238528)
addappid(3159335, 1, "843ebde3282fd10fe2204126d7be3c471c849e01618fd2419fd56be6a2e4fc72") -- German
setManifestid(3159335, "1102932231740758169", 1700724736)
addappid(3159336, 1, "10867627410a4ed3756f1263fe75741717e2c6f7797ff9af89cd7c5749a14f2b") -- Spanish
setManifestid(3159336, "4931157239490777827", 1748074496)
addappid(3159337, 1, "e4e59c05f264ffc35d4c0629f2f887bee3dc7848b240411d65a8f2e2d793843b") -- Brazilian
setManifestid(3159337, "175917902438003276", 1654456320)

-- DLC's (no depot keys required)
addappid(3362570) -- Assassin's Creed Shadows - Premium Starter Pack


-- DLC's (with depot keys)
-- Assassin's Creed Shadows - Claws of Awaji (AppID: 3362550)
addappid(3362550)
addappid(3159339, 1, "bf213689d9d9dbd0ec6f827e3af29ed5783bb4da152bbefe251a4af6197755f5") -- (windows, 64-bit)
setManifestid(3159339, "1250764753963549068", 21243597213)

-- Shared Depots (Runtimes / Launchers / ETC)
addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- (windows)
addappid(1716751, 1, "84780b728a23b1dabbe8b064807ccd3dbd40c67139ed569101104a418c581675")
setManifestid(1716751, "8936186649444731600", 264933784)

-- Missing Depots (We don't have the keys yet lol): 3362560
