-- PRAGMATA
-- Build ID: 22357085 - The launch for PRAGMATA is approaching! Watch the latest trailer!
-- Released 2026-04-15 01:59:30 UTC
-- This Lua was generated by LuaTools to support cerrtain shit

-- First let's add all the appids!
addappid(3357650)
addappid(3859920)
addappid(3859930)

-- Coolio now let's add the decryption keys we need!
addappid(3357651, 1, "18e75bfb3f8c26b7a59d9e3a7013e74e1c59fe563aa00ee15f54a35b17691766") -- PRAGMATA (base)
addappid(3357652, 1, "7421326d63bf53701559733582fe45877e218f41683ebc6d614905727f5ba144") -- PRAGMATA (base)
addappid(3859920, 1, "1fb811843160e2a11211f5bba90ece0ef2dac5994c19936e50ff85faf2f80423") -- PRAGMATA: Outfit Set - Neo Bushido & Neo Kunoichi
addappid(3859930, 1, "14001799a6877a14751af43adbd59ca3cc037cf202aa5615e0c70e057090ddce") -- PRAGMATA: Shelter Variety Pack

-- And last but not least, lock the depots to make shit work :3
setManifestid(3357651, "2417499809052404547")
setManifestid(3357652, "5639705324720691310")
setManifestid(3859920, "4731286747379700304")
setManifestid(3859930, "6714427611547107917")
