-- Stellar Blade™
-- 2026-06-12 04:40:35 UTC
-- This Lua was generated by LuaTools to support cerrtain shit

-- First let's add all the appids!
addappid(3489700)
addappid(3596170)
addappid(3596180)
addappid(3596190)
addappid(3596200)
addappid(3596210)
addappid(3596220)
addappid(3662250)

-- Coolio now let's add the decryption keys we need!
addappid(3489701, 1, "2266ca31f6f2666ebe75906201e72f9398694030ff1c8214aacebcf74dc94ee3") -- Stellar Blade™ (base)
addappid(3596180, 1, "a55f79607c32a7e24a388464ddc3cfbc91b2dcee6691061bca3fb32d231ccb32") -- Stellar Blade™ x NieR:Automata
addappid(3596190, 1, "1e65f8baa259f487dcdc1d3dce1e198dd23c9f7b77236e4e56fcc9f6b915a449") -- Stellar Blade™ x GODDESS OF VICTORY: NIKKE

-- And last but not least, lock the depots to make shit work :3
setManifestid(3489701, "2747626496734343426")
setManifestid(3596180, "8344797041293440177")
setManifestid(3596190, "6588499701851943951")
