-- 007 First Light
-- 2026-06-12 00:09:23 UTC
-- This Lua was generated by LuaTools to support cerrtain shit

-- First let's add all the appids!
addappid(3768760)
addappid(3950810)
addappid(3950820)
addappid(3950830)
addappid(3950850)
addappid(3950870)
addappid(3950880)
addappid(3950900)
addappid(3950910)
addappid(3950930)
addappid(3954230)
addappid(3954250)
addappid(3954260)
addappid(3986520)
addappid(4521800)
addappid(4521810)
addappid(4521820)
addappid(4521830)
addappid(4521840)
addappid(4601250)
addappid(4626160)
addappid(4707780)

-- Coolio now let's add the decryption keys we need!
addappid(3768761, 1, "8284c5e8921ec5acbe53f4d45af0260905841dc698ca179dd218ce5a2657ef09") -- 007 First Light (base)

-- And last but not least, lock the depots to make shit work :3
setManifestid(3768761, "7322178669849310269")
