-- Atomic Heart
-- Build ID: 23005793
-- This Lua was generated by LuaTools to support cerrtain shit manually lmao

-- Main AppID
addappid(668580, 1, "5a1ed8d8d2a8110fde9be6e0ec543d96db83954f381710c70e330b5c010841e7")

-- Main Depots
addappid(668581, 1, "b331448756a6614f7b9b52f56b71e329928370afb8034b8474e264ace0048928") -- (windows)
setManifestid(668581, "2756612790784314247", 169302013125)

-- DLC's (no depot keys required)
addappid(2214820) -- Atomic Heart - Midas Glove Skin
addappid(2214821) -- Atomic Heart - Annihilation Instinct
addappid(2214822) -- Atomic Heart - Trapped in Limbo
addappid(2214823) -- Atomic Heart - Enchantment Under the Sea
addappid(2214824) -- Atomic Heart - Blood On Crystal
addappid(2214826) -- Atomic Heart - Digital Artbook
addappid(2214830) -- Atomic Heart - Labor & Science Weapon Skin Pack
addappid(2214825) -- Atomic Heart - Golden Age Weapon Skin Pack

-- DLC's (with depot keys)
-- Atomic Heart - Original Soundtrack (AppID: 2303120)
addappid(2303120)
addappid(2303121, 1, "6fd3db1eba411d9ecc68741d7ebf12f38bfb738c8578dd71419af57f7b2f73c4")
setManifestid(2303121, "3587340790320923187", 852516865)
addappid(2303122, 1, "49808584cc51f185a98e76678db9045fcfccc7474b9bccb847a92aa223ed8aff")
setManifestid(2303122, "41228753438295057", 5122844316)

-- Shared Depots (Runtimes / Launchers / ETC)
addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- (windows)
addappid(228990, 1, "44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- (windows)

